import Layout from '@/components/Layout';

export const metadata = {
  title: 'Rogelio Vargas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <Layout>{ children }</Layout>
  )
}
