import App from './App';

export const metadata = {
  title: 'Rogelio Vargas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <App>{ children }</App>
  )
}
